<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IvkExportTool.Core\IvkExportTool.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
